FROM debian:trixie-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mkdir -p /app/logs /content

COPY target/release/tsbx-content /usr/local/bin/tsbx-content

EXPOSE 8000

CMD ["tsbx-content"]
